Repository civictheme/monorepo-drupal, pull requests merged in 2022-11, with the labels that each got.

#838 [CIVIC-942] Updated slider theme component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
  tests/behat/features/paragraph.civictheme_slider.view.feature
Labels: Needs review

#839 [CIVIC-1149] Updated banner title content wrap component.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
Labels: Needs review

#840 [CIVIC-1153] Updated navigation image component to be shown as icon.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_navigation_card.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_navigation_card.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_show_image_as_icon.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_show_image_as_icon.yml
  docroot/themes/contrib/civictheme/includes/navigation_card.inc
  tests/behat/features/paragraph.civictheme_navigation_card.fields.feature
Labels: Needs review

#841 [CIVIC-1152] Updated events content type display components.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml
  docroot/themes/contrib/civictheme/includes/cards.inc
Labels: Needs review

#842 [CIVIC-1150] Updated toc component styles.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.stories.js
Labels: Ready to be merged

#845 [CIVIC-1138] Converted components to use CSS variables. Part 1.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
Labels: Needs review

#847 [CIVIC-1150] Updated toc border to be on all sides for active state.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
Labels: Needs review

#848 [CIVIC-1153] Updated Image size to use large same as icon.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
Labels: Needs review

#852 [CIVIC-1189] Updated Navigation Card summary field to non-mandatory.
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_summary.yml
Labels: Needs review

#860 [CIVIC-1147] Updated footer block content text styles.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_government/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_government/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
Labels: Ready to be merged

#861 [CIVIC-1213] Removed summary field displayed from event content page.
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml
Labels: Ready to be merged

#862 [CIVIC-1136] Updated alert icon to be inline with alert title.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
Labels: Ready to be merged

#864 [CIVIC-1128] Updated campaign component drupal issues.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
Labels: Ready to be merged

#866 [CIVIC-1216] Implemented summary field config for events card component.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/optional/civictheme.settings.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/optional/civictheme.settings.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_government/config/optional/civictheme.settings.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/config/optional/civictheme.settings.yml
  docroot/themes/contrib/civictheme/config/install/civictheme.settings.yml
  docroot/themes/contrib/civictheme/config/schema/civictheme.schema.yml
  docroot/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php
Labels: Needs review

#833 [CIVIC-1125] Added schema, added migration mapping and validation for civictheme_page fields.
  composer.d10.lock
  composer.lock
  docroot/autoload.php
  docroot/modules/custom/civictheme_migrate/README.md
  docroot/modules/custom/civictheme_migrate/assets/migrations/content/migrate_plus.migration.civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/assets/migrations/media/migrate_plus.migration.civictheme_media_image.yml
  docroot/modules/custom/civictheme_migrate/assets/migrations/migrate_plus.migration.civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/assets/schema/civictheme_media.json
  docroot/modules/custom/civictheme_migrate/assets/schema/civictheme_page.json
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.info.yml
  docroot/modules/custom/civictheme_migrate/composer.json
  docroot/modules/custom/civictheme_migrate/config/schema/civictheme_migration.schema.yml
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateManager.php
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateValidator.php
  docroot/modules/custom/civictheme_migrate/src/Form/CivicthemeMigrateConfigurationForm.php
  docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/FileCopyDisposition.php
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_no_id_key.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_no_title_key.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_not_array_of_objects.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/valid_multiple_element.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/valid_single_element.json
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/CivicthemeMediaMigrateValidatorTest.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/CivicthemeMigrateValidatorBase.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/CivicthemeMigrateValidatorTest.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/CivicthemePageMigrateValidatorTest.php
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
  docroot/themes/contrib/civictheme/config/install/civictheme.settings.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/migrate.inc
  docroot/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionComponents.php
  tests/behat/features/migrate.feature
  tests/behat/features/theme.settings.components.feature
  tests/behat/fixtures/civictheme_migrate.media_content_1.json
  tests/behat/fixtures/civictheme_migrate.media_content_2.json
  tests/behat/fixtures/civictheme_migrate.page_content_1.json
  tests/behat/fixtures/civictheme_migrate.page_content_2.json
Labels: Needs review

#865 [CIVIC-1190] Updated list component.
  .circleci/config.yml
  CI.md
  README.md
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/dropdown-filter/dropdown-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
  docroot/themes/contrib/civictheme/includes/views.inc
  docroot/themes/contrib/civictheme/templates/views/views-view.html.twig
  renovate.json
  tests/behat/features/paragraph.civictheme_automated_list.render.feature
Labels: Ready to be merged

#867 Update All Contrib
  composer.d10.json
  composer.d10.lock
  composer.json
  composer.lock
  docroot/modules/custom/civictheme_migrate/composer.json
Labels: dependencies

#870 Updated Event dates to use components.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_government/content/node/d82c4982-b334-43ed-bfad-32ce5e63cba6.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.civictheme_event_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml
  docroot/themes/contrib/civictheme/templates/field/field--field-c-n-date.html.twig
Labels: Ready to be merged

#872 [CIVIC] Fixed mobile menu theme inheritance.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
Labels: Needs review

#873 [CIVIC-1241] Updated help text for Summary fields of cards.
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_event_card.field_c_p_summary.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_summary.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_promo.field_c_p_summary.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_promo_card.field_c_p_summary.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_publication_card.field_c_p_summary.yml
Labels: Needs review

#874 [CIVIC-1245] Fix A11Y issue Flyout component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/flyout/flyout.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
Labels: DO NOT MERGE, Needs review

#880 [CIVIC] Fixed banner typo.
  docroot/themes/contrib/civictheme/includes/banner.inc
Labels: Needs review

#881 [CIVIC-1273] Fixed issues raised on Higher Education profile for civic theme.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/35b75cc7-cf94-462f-9ee6-6bb69e895d8a.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/43d8c204-e1e5-436c-b23a-861a2f2f743a.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/8f45163f-252f-46e3-b3d3-7930b1d9b6c7.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/bbd57889-e07c-4c4f-a223-868f9a441035.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/c9a1fe64-f6d1-4492-ac7f-6444698cfb12.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/ee025f20-7976-47b2-aa62-a00b84b149de.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
Labels: Needs review
