Repository civictheme/monorepo-drupal, pull requests merged in 2022-12, with the labels that each got.

#882 [CIVIC-1286] Updated Subject card to not require image and fixed arrow.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_highereducation/content/node/8f45163f-252f-46e3-b3d3-7930b1d9b6c7.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_subject_card.field_c_p_image.yml
  tests/behat/features/paragraph.civictheme_subject_card.fields.feature
Labels: Ready to be merged

#889 [CIVIC-1260] Updated `Item grid` to use unordered list.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.twig
  tests/behat/features/content_type.civictheme_page.render.feature
  tests/behat/features/paragraph.civictheme_manual_list.render.feature
Labels: Needs review

#886 [CIVIC-1284] Updated promo button size ito be based on text length.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.scss
Labels: Needs review

#875 [CIVIC-1248] Added aria label to menu icon buttons.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
Labels: Needs review

#891 [CIVIC-1292] Updated reference slider component to have a custom button link.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_slider_slide_ref.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_slider_slide_ref.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_slider_slide_ref.field_c_p_link_text.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_link_text.yml
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_slider_slide_ref.yml
  docroot/themes/contrib/civictheme/includes/slider.inc
  tests/behat/features/paragraph.civictheme_slider.fields.feature
  tests/behat/features/paragraph.civictheme_slider.render.feature
Labels: Needs review

#890 [CIVIC-1291] Updated content Link processing to process all links.
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
Labels: Needs review

#885 [CIVIC-1288] Removed the unused icon usage.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
Labels: State: Needs review

#887 [CIVIC-1264] Updated Title field in all cards to render as Heading component of level 4.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig
Labels: State: Needs review

#830 [CIVIC-1047] Updated collapsible to work same on spacebar and enter keys.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js
Labels: State: Requires more work

#904 [CIVIC-1242] Updated Navigation titles to correct heading H2.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.twig
Labels: State: Needs review

#905 [CIVIC-1313] Updated Next steps content component.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/component.next_step.inc
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_link.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_summary.yml
  tests/behat/features/paragraph.civictheme_next_step.fields.feature
Labels: State: Needs review

#907 [CIVIC-1314] Updated banner block component to add Type and Featured image fields.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.block_content.civictheme_banner.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.block_content.civictheme_banner.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_banner.field_c_b_banner_type.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_banner.field_c_b_featured_image.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_banner_type.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_featured_image.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
  tests/behat/features/block_type.civictheme_banner.fields.feature
  tests/behat/features/block_type.civictheme_banner.render.feature
Labels: State: Needs review

#908 [CIVIC-1034] Fixed Field label - Storybook : font-size as per Figma.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
Labels: State: Needs review

#906 [CIVIC-1312] Applied vertical tabs patch.
  composer.json
  composer.lock
  tests/behat/features/theme.settings.vertical_tabs.feature
Labels: State: Ready to be merged

#883 [CIVIC-1235] Fixed Pager to prevent html output if no content.
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/paragraph.civictheme_automated_list.render.feature
Labels: State: Ready to be merged

#911 [CIVIC-1257] Updated menu to communicate the state: A11Y
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
Labels: State: Needs review

#888 [CIVIC-1232] Tags implementation.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_hide_tags.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_hide_tags.yml
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/templates/misc/tag-list.html.twig
  tests/behat/features/content_type.civictheme_page.render.feature
Labels: State: Needs review

#912 [CIVIC-1268] Updated title to use heading and no div wrap.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.twig
  tests/behat/features/migrate.feature
Labels: State: Needs review

#914 [CIVIC-1323] Updated card headings to remove overrides.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
Labels: State: Ready to be merged

#915 [CIVIC-1257] Updated mobile menu to communicate the state: A11Y
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
Labels: State: Needs review

#916 [CIVIC-1324] Fixed how icon markup is added to Buttons, Link and Tag.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.twig
  tests/behat/features/paragraph.civictheme_manual_list.render.feature
Labels: State: Ready to be merged

#919 Unified calls to breakpoint mixin.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_content.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/single-filter/single-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.scss
Labels: State: Ready to be merged

#920 Removed Styleguide in favour of generated content.
  .docker/Dockerfile.cli
  .docker/Dockerfile.cli.onlytheme
  .docker/Dockerfile.cli.sibling
  composer.d10.json
  composer.d10.lock
  composer.json
  composer.lock
  docroot/modules/custom/civictheme_dev/civictheme_dev.info.yml
  docroot/modules/custom/civictheme_dev/civictheme_dev.post_update.php
  docroot/modules/custom/civictheme_styleguide/civictheme_styleguide.info.yml
  docroot/modules/custom/civictheme_styleguide/civictheme_styleguide.module
  docroot/modules/custom/civictheme_styleguide/components/callout.inc
  docroot/modules/custom/civictheme_styleguide/components/figure.inc
  docroot/modules/custom/civictheme_styleguide/components/page_title.inc
  docroot/modules/custom/civictheme_styleguide/components/promo.inc
  docroot/modules/custom/civictheme_styleguide/components/quote.inc
  docroot/modules/custom/civictheme_styleguide/components/video_player.inc
  docroot/modules/custom/civictheme_styleguide/composer.json
  docroot/modules/custom/civictheme_styleguide/src/Styleguide.php
  docroot/modules/custom/civictheme_styleguide/templates/styleguide-header.html.twig
  docroot/modules/custom/civictheme_styleguide/templates/styleguide-item.html.twig
  docroot/modules/custom/civictheme_styleguide/templates/styleguide-links.html.twig
  tests/behat/features/pagination.render.feature
  tests/behat/features/table.render.feature
Labels: State: Ready to be merged

#921 Updated D10 packages.
  composer.d10.json
  composer.d10.lock
  docroot/robots.txt
Labels: State: Ready to be merged
