Repository civictheme/monorepo-drupal, pull requests merged in 2022-09, with the labels that each got.

#609 [CIVIC-813] Updated select storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.twig
Labels: Needs review

#599 [CIVIC-798] Added a new field message atom component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
Labels: Needs review

#611 [CIVIC-777] Updated icons from the latest Figma export.
  docroot/themes/contrib/civictheme/civictheme_library/assets/icons/checked.svg
  docroot/themes/contrib/civictheme/civictheme_library/assets/icons/select-box.svg
Labels: Needs review

#615 [CIVIC-804] Updated Textarea component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.twig
Labels: Ready to be merged

#618 [CIVIC-996] Updated PHP to 8.1
  .docker/Dockerfile.cli
  .docker/Dockerfile.cli2
  .docker/Dockerfile.php
  composer.json
  composer.lock
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/theme-settings.php
Labels: Needs review

#622 [CIVIC-798] Fixed icons for errors in a storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
Labels: Needs review

#623 [CIVIC-995] Fixed is-external and right-arrow icons.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo/promo.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
Labels: Needs review

#621 Update All Contrib
  composer.json
  composer.lock
  docroot/themes/contrib/civictheme/civictheme_library/scripts/extract_css_colors_to_csv.php
  renovate.json
Labels: dependencies

#625 [CIVIC-786] Fixed default value for Table component in Storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.stories.js
Labels: Needs review

#626 [CIVIC-804] Minimum width and border radius.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.scss
Labels: Needs review

#628 [CIVIC-998] Updated icon scss to handle theme style color.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_icon.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.scss
Labels: Needs review

#627 Update All Contrib
  composer.lock
Labels: dependencies

#616 [CIVIC-783] Updated link storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
Labels: Needs review

#619 [CIVIC-813] Updated storybook select component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.twig
Labels: Ready to be merged

#636 [CIVIC-998] Fixed Icon colour to match the border colour of the Field message.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
Labels: Ready to be merged

#635 [CIVIC-1001] Fix tab order.
  docroot/themes/contrib/civictheme/includes/local_tasks.inc
Labels: Ready to be merged

#632 [CIVIC-1000] Updated code to 'cleancode' PHPMD standards.
  .env
  docroot/themes/contrib/civictheme/civictheme_create_subtheme.php
  docroot/themes/contrib/civictheme/civictheme_starter_kit/scripts/add_phpcs_exclusions.php
  docroot/themes/contrib/civictheme/civictheme_starter_kit/scripts/update_config.php
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/html.inc
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/includes/listing.inc
  docroot/themes/contrib/civictheme/includes/media.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  docroot/themes/contrib/civictheme/package.json
  docroot/themes/contrib/civictheme/tests/src/Traits/CivicThemeTestHelperTrait.php
  docroot/themes/contrib/civictheme/theme-settings.php
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
Labels: Ready to be merged

#640 [CIVIC-779] Implemented support to provide alt text if the icon is rendered in HTML mode.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.twig
Labels: Needs review

#629 [CIVIC-1003] Added licenses and removed lock files for cleaner builds.
  .docker/Dockerfile.cli
  .docker/Dockerfile.cli2
  .gitignore
  docroot/themes/contrib/civictheme/civictheme_library/.gitignore
  docroot/themes/contrib/civictheme/civictheme_library/package-lock.json
  docroot/themes/contrib/civictheme/civictheme_library/package.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package-lock.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package.json
  docroot/themes/contrib/civictheme/composer.json
  docroot/themes/contrib/civictheme/package-lock.json
  docroot/themes/contrib/civictheme/package.json
  scripts/custom/drupal-install-site-2-activate-subtheme.sh
  tests/phpunit/unit/CivicthemeCreateSubthemeScriptUnitTest.php
Labels: Ready to be merged

#634 Fixed handling of empty exposed filters in Listing component.
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
Labels: Ready to be merged

#638 [CIVIC-785] Updated Link component for accessibility
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/visibility/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/directional-link/directional-link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/skip-link/skip-link.twig
  docroot/themes/contrib/civictheme/templates/navigation/menu-local-tasks.html.twig
Labels: Ready to be merged

#639 [CIVIC-791] Updated Tag component for accessibility.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.twig
Labels: Needs review

#641 [CIVIC-773] Updated Button component for accessibility
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
Labels: Needs review

#642 [CIVIC-983] Updated content link component for accessibility.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.twig
Labels: Needs review

#624 [CIVIC-774] Refactored Chip component.
  docroot/themes/contrib/civictheme/.storybook/theme.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.stories.event.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig
  tests/behat/features/view.civictheme_listing_examples.feature
Labels: Needs review

#645 [CIVIC-1007] Fixed invalid URLs triggering errors when parsing external links.
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeHtmlLinkUnitTest.php
  tests/behat/features/links.feature
Labels: Ready to be merged

#648 [CIVIC-771] Updated button story book component styles.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss
Labels: Needs review

#650 [CIVIC-885] Updated video player story book component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig
Labels: Needs review

#649 [CIVIC-1002] Fixed not rendering exposed text filters on views
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/paragraph.civictheme_listing.view.feature
  tests/behat/features/view.civictheme_listing_examples.feature
Labels: Needs review, Question

#652 [CIVIC-879] Updated skip link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_visibility.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/skip-link/skip-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/skip-link/skip-link.twig
Labels: Needs review

#655 [CIVIC-787] Part-1: Added styleguide module.
  composer.json
  composer.lock
  docroot/modules/custom/cs_core/cs_core.info.yml
Labels: Needs review

#654 [CIVIC-873] Updated Promo storybook component
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-promo.html.twig
Labels: Needs review

#658 [CIVIC-813] Updated select storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
Labels: Needs review

#666 Update All Contrib
  composer.lock
Labels: dependencies

#653 [CIVIC-780] Updated Typography component story.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/typography.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/typography.stories.twig
Labels: Needs review

#661 [CIVIC-825] Updated the back to top component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.twig
Labels: Needs review

#663 [CIVIC-951] Updated Tabs component storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.twig
  docroot/themes/contrib/civictheme/templates/navigation/menu-local-tasks.html.twig
Labels: Needs review

#665 [CIVIC-1010] Moved icon and background to the base component.
  docroot/themes/contrib/civictheme/.storybook/main.js
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/main.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/background/background.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/background/background.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/background/background.utils.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/icon/icon.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/icon/icon.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/icon/icon.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/icon/icon.utils.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/directional-link/directional-link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/figure/figure.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/progress-indicator/progress-indicator.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/breadcrumb/breadcrumb.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.stories.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.storybook/main.js
Labels: Needs review

#667 [CIVIC-879] Updated skip link storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/skip-link/skip-link.scss
Labels: Needs review

#662 [CIVIC-772] Added civictheme-button classes to button links.
  docroot/themes/contrib/civictheme/includes/form.inc
Labels: Ready to be merged

#657 [CIVIC-861] Updated logo storybook component.
  docroot/themes/contrib/civictheme/.storybook/theme.js
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_primary_dark_desktop.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_primary_dark_mobile.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_primary_light_desktop.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_primary_light_mobile.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_secondary_dark_desktop.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_secondary_dark_mobile.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_secondary_light_desktop.png
  docroot/themes/contrib/civictheme/assets/logos/civictheme_logo_secondary_light_mobile.png
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/theme.js
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_primary_dark_desktop.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_primary_dark_mobile.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_primary_light_desktop.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_primary_light_mobile.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_secondary_dark_desktop.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_secondary_dark_mobile.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_secondary_light_desktop.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/logos/civictheme_logo_secondary_light_mobile.png
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.utils.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.stories.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.storybook/theme.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_primary_dark_desktop.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_primary_dark_mobile.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_primary_light_desktop.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_primary_light_mobile.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_secondary_dark_desktop.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_secondary_dark_mobile.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_secondary_light_desktop.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/logos/civictheme_starter_kit_logo_secondary_light_mobile.png
  docroot/themes/contrib/civictheme/includes/system_branding.inc
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
Labels: Needs review

#671 [CIVIC-783] Updated civic theme link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
Labels: Needs review

#656 [CIVIC-787] Table integration.
  docroot/modules/custom/cs_core/config/install/views.view.civictheme_test_table.yml
  docroot/modules/custom/cs_core/cs_core.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/includes/pager.inc
  docroot/themes/contrib/civictheme/includes/table.inc
  docroot/themes/contrib/civictheme/templates/dataset/table.html.twig
  docroot/themes/contrib/civictheme/templates/views/views-view-table.html.twig
  tests/behat/features/table.view.feature
Labels: Needs review

#673 [CIVIC-1011] Implemented item list storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.twig
Labels: Needs review, Question

#668 [CIVIC-882] Updated tooltip component with popperjs.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.twig
  docroot/themes/contrib/civictheme/civictheme_library/package.json
  docroot/themes/contrib/civictheme/civictheme_library/webpack/libraries.js
  docroot/themes/contrib/civictheme/civictheme_library/webpack/webpack.common.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/webpack/libraries.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/webpack/webpack.common.js
  docroot/themes/contrib/civictheme/package.json
  docroot/themes/contrib/civictheme/webpack/libraries.js
  docroot/themes/contrib/civictheme/webpack/webpack.common.js
Labels: Needs review

#674 [CIVIC-867] Updated pagination component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/directional-link/directional-link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
Labels: Ready to be merged

#679 [CIVIC-1008] Fixed external link icon added when 'is external' option is unchecked.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
Labels: Needs review

#675 [CIVIC-891] Added Quote component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.twig
Labels: Ready to be merged

#682 [CIVIC-1020] Removed password strength indicator component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.stories.twig
Labels: Needs review

#683 [CIVIC-1016] Removed any custom CSS overrides from the Table component for links.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_table.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.stories.js
Labels: Ready to be merged

#672 [CIVIC-973] Refactored colours to use new colour scheme.
  docroot/themes/contrib/civictheme/.storybook/importer.scss_variables.js
  docroot/themes/contrib/civictheme/assets/sass/header/_header.scss
  docroot/themes/contrib/civictheme/civictheme_library/.eslintrc.yml
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/importer.scss_variables.js
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/preview.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/colors/colors.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/colors/colors.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/colors/colors.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_color.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_form.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_outline.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_table.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/responsive/responsive.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/responsive/responsive.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/scrollspy/scrollspy.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/typography.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/icon/icon.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/input/input.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/directional-link/directional-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/dropdown-filter/dropdown-filter.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/figure/figure.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/package.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.storybook/importer.scss_variables.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/components/variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_starter_kit/components/variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package.json
  docroot/themes/contrib/civictheme/package.json
  scripts/drevops/lint.sh
Labels: Ready to be merged

#689 [CIVIC-1019] Implemented blend mode per-page.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_blend_mode.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_blend_mode.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
Labels: Ready to be merged

#690 [CIVIC-862] Updated Drupal logo component.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.stories.twig
  docroot/themes/contrib/civictheme/config/schema/civictheme.schema.yml
  docroot/themes/contrib/civictheme/includes/constants.inc
  docroot/themes/contrib/civictheme/includes/system_branding.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/templates/block/block--system-branding-block.html.twig
  docroot/themes/contrib/civictheme/theme-settings.php
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
  tests/behat/features/theme.settings.feature
  tests/behat/features/theme.settings.storybook.feature
Labels: Needs review

#691 [CIVIC-939] Updated table of content storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.stories.js
Labels: Ready to be merged

#693 [CIVIC-891] Quote typography fix.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/quote/quote.scss
Labels: Needs review

#694 [CIVIC-1004] Border radius fix.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.js
Labels: Needs review

#695 [CIVIC-1006] Updated popover accessibility.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.js
Labels: Needs review

#696 [CIVIC-884] Updated tooltip design and accessibility.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.twig
Labels: Ready to be merged

#697 [CIVIC-867] Updated Pagination design and added accessibility title.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
Labels: Ready to be merged

#699 [CIVIC-992] Fixed layout classes for mobile.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/grid/grid.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_grid.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-filter/basic-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/map/map.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/card-container/card-container.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/fieldset/fieldset.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/04-templates/page/page.twig
Labels: Needs review

#700 [CIVIC-984] Removed the rogue class layout-container.
  docroot/themes/contrib/civictheme/civictheme_library/components/04-templates/page/page.twig
Labels: Needs review

#701 [CIVIC-942] Updated slider storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.twig
Labels: Needs review

#703 [CIVIC-1032] Updated storybook skip link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/skip-link/skip-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/skip-link/skip-link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/skip-link/skip-link.twig
  docroot/themes/contrib/civictheme/templates/layout/html.html.twig
Labels: Needs review

#706 [CIVIC-1019] Added generator class for blend mode.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/background/background.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/pager.inc
Labels: Ready to be merged

#709 [CIVIC-939] Updated toc component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.scss
Labels: Needs review

#712 Fixed example view machine name.
  docroot/modules/custom/cs_core/config/install/block.block.civictheme_automated_list_examples_page_one_filter_single_select_exp.yml
  docroot/modules/custom/cs_core/cs_core.info.yml
  docroot/modules/custom/cs_core/cs_core.post_update.php
  scripts/theme_excluded_configs.txt
Labels: Ready to be merged

#716 [CIVIC-1048] Update Automated List fields.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_automated_list.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_automated_list.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_component_block.field_c_b_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_components_bott.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_column_count.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_content.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_fill_width.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_link_above.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_link_below.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_type.yml
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_automated_list.yml
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_social_icon.yml
  docroot/themes/contrib/civictheme/config/install/views.view.civictheme_automated_list.yml
  tests/behat/features/paragraph.civictheme_automated_list.fields.feature
Labels: Ready to be merged

#719 [CIVIC-1049] Added a new component Item Grid to storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-grid/item-grid.twig
Labels: Needs review

#717 [CIVIC-924] Updated Status to be Information.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_alert_type.yml
  tests/behat/features/content_type.civictheme_alert.view.feature
Labels: Ready to be merged

#708 [CIVIC-892] Added Quote component Drupal integration.
  docroot/modules/custom/civictheme_styleguide/components/quote.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/quote/quote.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_quote.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_quote.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_quote.field_c_p_author.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_quote.field_c_p_content.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_quote.field_c_p_space.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_quote.field_c_p_theme.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_author.yml
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_quote.yml
  docroot/themes/contrib/civictheme/includes/quote.inc
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-quote.html.twig
  scripts/theme_excluded_configs.txt
  tests/behat/features/paragraph.civictheme_quote.fields.feature
  tests/behat/features/paragraph.civictheme_quote.view.feature
Labels: Ready to be merged

#718 [CIVIC-1041] Rearranged components.
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/preview.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/spacing/spacing.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/spacing/spacing.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/callout/callout.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/callout/callout.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/callout/callout.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/form-element/form-element.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/form-element/form-element.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/form-element/form-element.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/basic-filter/basic-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/basic-filter/basic-filter.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/basic-filter/basic-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/04-templates/page/page.twig
  docroot/themes/contrib/civictheme/civictheme_starter_kit/templates/form/input--submit.html.twig
  docroot/themes/contrib/civictheme/templates/form/checkboxes--civictheme-basic-filter.html.twig
  docroot/themes/contrib/civictheme/templates/form/form-element--civictheme-dropdown-filter.html.twig
  docroot/themes/contrib/civictheme/templates/form/form-element.html.twig
  docroot/themes/contrib/civictheme/templates/form/input--submit.html.twig
  docroot/themes/contrib/civictheme/templates/form/radios--civictheme-basic-filter.html.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-accordion.html.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-callout.html.twig
Labels: Ready to be merged

#720 [CIVIC-901] Callout component Styleguide integration.
  docroot/modules/custom/civictheme_styleguide/components/callout.inc
Labels: Needs review

#722 [CIVIC-859] Figure component Styleguide integration.
  docroot/modules/custom/civictheme_styleguide/components/figure.inc
  docroot/modules/custom/civictheme_styleguide/src/Styleguide.php
Labels: Ready to be merged

#724 Update All Contrib
  composer.lock
Labels: dependencies

#726 [CIVIC-867] Updated pagination component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
Labels: Ready to be merged

#731 [CIVIC-852] Updated service card to use Content link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.twig
Labels: Needs review

#723 [CIVIC-1063] Removed link list component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/link-list/link-list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/link-list/link-list.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/link-list/link-list.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.twig
Labels: Needs review

#730 [CIVIC-924] Updated message storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
Labels: Requires more work

#742 Fixed alert test after CivicTheme renaming.
  docroot/themes/contrib/civictheme/includes/alert.inc
  tests/behat/features/content_type.civictheme_alert.view.feature
Labels: Needs review

#734 [CIVIC-1032] Reduced variants of listing and banner.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/02.automated_list.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/02.banner.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/04.banner.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/04.component.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/05.component.accordion.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/06.component.attachment.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/07.component.callout.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/08.component.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/09.component.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/10.component.next_step.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/11.component.promo.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/12.component.automated_list.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/13.component.automated_list.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/13.component.webform.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/14.component.slider.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/15.component.card_container.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/17.banner_component.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/18.banner_component.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/20.banner_component.card_container.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/21.banner_component.slider.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/22.banner_component.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/23.banner_component.search.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/24.banner_components_bott.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/25.banner_components_bott.accordion.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/26.banner_components_bott.callout.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/27.banner_components_bott.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/28.banner_components_bott.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/29.banner_components_bott.promo.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/30.banner_components_bott.automated_list.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/31.banner_components_bott.webform.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/32.banner_components_bott.slider.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/33.banner_components_bott.card_container.inc
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
Labels: Ready to be merged

#727 [CIVIC-1063] Updated List component.
  docroot/themes/contrib/civictheme/assets/js/civictheme-ajax-views.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/chip/chip.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
  docroot/themes/contrib/civictheme/includes/views.inc
  docroot/themes/contrib/civictheme/templates/form/checkboxes--civictheme-single-filter.html.twig
  docroot/themes/contrib/civictheme/templates/form/form-element--civictheme-filter-chip.html.twig
  docroot/themes/contrib/civictheme/templates/form/radios--civictheme-single-filter.html.twig
  docroot/themes/contrib/civictheme/templates/views/views-view-grid.html.twig
  tests/behat/features/paragraph.civictheme_automated_list.view.feature
  tests/behat/features/view.civictheme_automated_list_examples.feature
Labels: Needs review

#743 Fixed failing tests.
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  tests/behat/features/paragraph.civictheme_accordion.view.feature
  tests/behat/features/paragraph.civictheme_attachment.view.feature
  tests/behat/features/paragraph.civictheme_content.view.feature
  tests/behat/features/paragraph.civictheme_iframe.view.feature
  tests/behat/features/paragraph.civictheme_map.view.feature
  tests/behat/features/theme.settings.feature
Labels: Needs review

#739 [CIVIC-886] Added video media to style-guide Drupal.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/760a6a1c-cace-42a3-91f2-2c0f2b76ea3c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/media/0953800f-c751-4943-af5e-ed5ff82422a9.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/608b3d31-cd63-420e-8342-9c210fbb7538.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/84cb6edd-4ced-4a05-8c7b-e481cff41ce6.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/a15b6d80-d397-466b-be74-4573eba1b6b2.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/f1b362fc-1208-4136-9ceb-cd2f534a4141.yml
  docroot/modules/custom/civictheme_styleguide/components/video_player.inc
  docroot/modules/custom/cs_generated_content/generated_content/file/file.inc
  docroot/modules/custom/cs_generated_content/generated_content/media/civictheme_video.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/02.banner.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/09.component.map.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/map/map.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/map/map.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_remote_video.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_remote_video.media_library.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_video.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_video.media_library.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_map.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.full.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.media_library.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.full.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.media_library.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_map.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.media.civictheme_remote_video.field_c_m_share_link.yml
  docroot/themes/contrib/civictheme/config/install/field.field.media.civictheme_video.field_c_m_share_link.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_map.field_c_p_share_link.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.media.field_c_m_share_link.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_share_link.yml
  docroot/themes/contrib/civictheme/includes/map.inc
  docroot/themes/contrib/civictheme/includes/media.inc
  docroot/themes/contrib/civictheme/templates/media/media--civictheme-video--full.html.twig
  tests/behat/features/paragraph.civictheme_map.fields.feature
  tests/behat/features/paragraph.civictheme_map.view.feature
Labels: Requires more work

#738 [CIVIC-888] Updated breadcrumb component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/item-list/item-list.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.twig
  tests/behat/features/breadcrumb.view.feature
Labels: Ready to be merged

#747 Update All Contrib
  composer.lock
Labels: dependencies

#753 [CIVIC-1085] Updated footer story book component.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.twig
Labels: Needs review

#749 [CIVIC-921] Updated alert && message component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
Labels: Needs review

#751 [CIVIC-1080] Updated next steps component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.twig
  tests/behat/features/paragraph.civictheme_next_step.view.feature
Labels: Ready to be merged

#750 [CIVIC-840] [CIVIC-846] Updated Event and Promo card components to use link component for title.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  tests/behat/features/content_type.civictheme_page.view.feature
  tests/behat/features/paragraph.civictheme_card_container.view.feature
Labels: Ready to be merged

#756 [CIVIC-1074] Added Particle element and updated all measurements to use it.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/colors/colors.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/elevation/elevation.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/flyout/flyout.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/fonts.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/grid/grid.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_content.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_debug.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_form.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_highlight.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_icon.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_particle.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_spacing.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_table.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_visibility.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/scrollspy/scrollspy.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-message/field-message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/input/input.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/radio/radio.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/select/select.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textarea/textarea.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/textfield/textfield.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/dropdown-filter/dropdown-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tabs/tabs.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/tooltip/tooltip.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/back-to-top/back-to-top.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/secondary-navigation/secondary-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/social-links/social-links.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/table-of-contents/table-of-contents.scss
Labels: Ready to be merged

#757 [CIVIC-888] Fixed regression issue of Link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
Labels: Needs review

#758 [CIVIC-938] Implemented Skip to content for side navigation.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.twig
Labels: Needs review

#759 [CIVIC-822] Updated attachment components.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
Labels: Needs review

#761 [CIVIC-921] Fixed alert dark colors.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
Labels: Needs review

#763 [CIVIC-936] Updated side navigation storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/side-navigation/side-navigation.scss
Labels: Needs review

#764 [CIVIC-841] Updated event card logo.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
Labels: Needs review

#766 [CIVIC-927] Fixed mobile navigation icons and missing parent item.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-close.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
Labels: Needs review

#768 [CIVIC-1092] [CIVIC-927] Updated breadcrumb component && Fixed mobile navigation icons colours.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.scss
Labels: Needs review

#769 [CIVIC-846] Updated promo and event tags type.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
Labels: Needs review

#772 Update All Contrib
  composer.lock
Labels: dependencies

#771 Update dependency drush/drush to v11.2.1
  composer.lock
Labels: dependencies

#767 [CIVIC-876] Updated popover storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/popover/popover.twig
Labels: Needs review
