Repository civictheme/monorepo-drupal, pull requests merged in 2022-06, with the labels that each got.

#438 [CIVIC-591] Included data attributes to control Accordion component.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.twig
  tests/behat/features/paragraph.civictheme_accordion.view.feature
Labels: Needs review

#446 [CIVIC-617] Fixed button focus issue.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.js
Labels: Needs review

#448 [CIVIC-651] Updated Accordion to use Collapsible to control state.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.twig
  tests/behat/features/paragraph.civictheme_accordion.view.feature
Labels: Needs review

#445 [CIVIC-607] Form element description template.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.twig
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/templates/form/input--submit.html.twig
Labels: Needs review

#456 [CIVIC-646] Added permissions to manage Webforms to Site administrator role
  docroot/themes/contrib/civictheme/config/install/user.role.civictheme_site_administrator.yml
  tests/behat/features/webform.civictheme_site_administrator.permissions.feature
Labels: Needs review

#454 [CIVIC-652] Remove title from accordion paragraph.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_accordion.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_accordion.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_accordion.field_c_p_title.yml
  docroot/themes/contrib/civictheme/includes/accordion.inc
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/paragraph.civictheme_accordion.fields.feature
  tests/behat/features/paragraph.civictheme_accordion.view.feature
Labels: Requires more work

#455 [CIVIC-607] Updated link component to use hidden_text.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
Labels: Needs review

#461 [CIVIC-668] Updated function logic of Banner breadcrumb theme to allow overridden from page
  docroot/themes/contrib/civictheme/includes/banner.inc
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Ready to be merged

#465 Add additional replacements of relative paths.
  docroot/themes/contrib/civictheme/civictheme_create_subtheme.php
  docroot/themes/contrib/civictheme/civictheme_library/scripts/extract_css_colors_to_csv.php
Labels: Needs review

#464 [CIVIC-517] Added offset for in-page links so they are not hidden behind sticky header.
  docroot/themes/contrib/civictheme/assets/sass/header/_header.scss
  docroot/themes/contrib/civictheme/assets/sass/theme.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
Labels: Needs review

#468 [CIVIC-675] Fixed external menu link intergration.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig
  docroot/themes/contrib/civictheme/includes/menu.inc
  docroot/themes/contrib/civictheme/includes/primary_navigation.inc
  docroot/themes/contrib/civictheme/includes/secondary_navigation.inc
  docroot/themes/contrib/civictheme/templates/block/block--menu-block--civictheme-footer.html.twig
Labels: Needs review

#467 [CIVIC-674] Fixed logos not handling public stream wrappers as value in theme settings.
  docroot/themes/contrib/civictheme/theme-settings.php
  tests/behat/features/theme.settings.feature
Labels: Needs review

#469 Fixed Drupal behaviours being generated with name collisions.
  docroot/themes/contrib/civictheme/civictheme_starter_kit/components/01-atoms/demo-button/demo-button.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/gulpfile.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package-lock.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/package.json
  docroot/themes/contrib/civictheme/civictheme_starter_kit/webpack/babel-plugin-drupal-behavior-wrapper.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/webpack/webpack.common.js
  docroot/themes/contrib/civictheme/package-lock.json
  docroot/themes/contrib/civictheme/package.json
  docroot/themes/contrib/civictheme/webpack/babel-plugin-drupal-behavior-wrapper.js
  docroot/themes/contrib/civictheme/webpack/webpack.common.js
Labels: Needs review

#474 [CIVIC-675] Mobile navigation external icon fix.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
Labels: Needs review

#473 [CIVIC-683] Button to restrict with regular icon only.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
Labels: Needs review

#475 Update All Contrib
  composer.lock
Labels: dependencies

#478 [CIVIC-685] Added components to demo content.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/05.component.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/07.component.attachment.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/08.component.callout.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/09.component.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/10.component.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/11.component.next_step.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/12.component.promo.inc
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
Labels: Needs review

#476 Update dependency govcms/govcms to v2.16.0
  composer.lock
Labels: dependencies

#479 [CIVIC-685] Added components to demo content.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/13.component.listing.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/14.component.webform.inc
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentHelper.php
Labels: Needs review

#477 [CIVIC-680] Added a colour map CSV link to Storybook.
  docroot/themes/contrib/civictheme/.eslintrc.yml
  docroot/themes/contrib/civictheme/.storybook/main.js
  docroot/themes/contrib/civictheme/civictheme_library/.eslintrc.yml
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/main.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/colors/colors.stories.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.eslintrc.yml
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.storybook/main.js
Labels: Needs review

#481 [CIVIC-685] Added components to demo content.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/16.component.card_container.inc
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
Labels: Needs review

#485 [CIVIC-647] Added show last updated field and related preprocess func…
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_show_last_updated.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_show_last_updated.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/templates/misc/basic-content.html.twig
  tests/behat/features/content_type.civictheme_page.fields.feature
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Requires more work

#470 [CIVIC-638] Refactored blocks configuration
  docroot/modules/custom/civictheme_content/civictheme_content.install
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/config/install/block.block.civictheme_signup.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_signup.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/civictheme_default_config.info.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_signup.yml
  docroot/themes/contrib/civictheme/civictheme.info.yml
  tests/behat/features/civictheme_page.blocks.feature
Labels: Ready to be merged

#484 [CIVIC-682] Search link implementation.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.stories.twig
  docroot/themes/contrib/civictheme/config/install/block_content.type.civictheme_search.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.block_content.civictheme_search.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_search.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.block_content.civictheme_search.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_search.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_search.field_c_b_link.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_button_text.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_help_text.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_placeholder.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_search_url.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_theme.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_search.field_c_p_title.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_link.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_button_text.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_help_text.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_placeholder.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_search_url.yml
  docroot/themes/contrib/civictheme/includes/search.inc
  docroot/themes/contrib/civictheme/templates/block/block--civictheme-search--default.html.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-search.html.twig
  tests/behat/features/block_type.civictheme_search.fields.feature
  tests/behat/features/paragraph.civictheme_search.fields.feature
Labels: Needs review

#486 Update All Contrib
  composer.lock
Labels: dependencies

#489 [CIVIC-676] Fixed position of header top 3 region.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.twig
Labels: Ready to be merged

#491 [CIVIC-696] Added banner and banner bottom component variations for demo content.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/17.banner_component.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/18.banner_component.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/20.banner_component.card_container.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/21.banner_component.slider.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/22.banner_component.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/23.banner_component.search.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/24.banner_components_bott.content.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/25.banner_components_bott.accordion.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/26.banner_components_bott.callout.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/27.banner_components_bott.iframe.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/28.banner_components_bott.map.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/29.banner_components_bott.promo.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/30.banner_components_bott.listing.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/31.banner_components_bott.webform.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/32.banner_components_bott.slider.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/33.banner_components_bott.card_container.inc
  docroot/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
Labels: Needs review

#492 [CIVIC-625] Fixed missing blocks warnings.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/config/install/block.block.civictheme_signup.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/install/block.block.civictheme_signup.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_acknowledgmentofcountry.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_banner.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_copyright.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_footer_social_links.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_mobile_navigation.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_default_config/config/optional/block.block.civictheme_signup.yml
Labels: Needs review

#496 Fixed typos on Video component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/video/video.twig
Labels: Needs review

#497 [CIVIC] Fixed wrong color reference on Primary navigation.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss
Labels: Needs review

#498 [CIVIC] Fixed mobile navigation trigger modifier class bug.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-trigger.twig
Labels: Ready to be merged

#500 [CIVIC-701] Fixed HTML tags rendering for Promo Card with Event CT
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
Labels: Needs review

#504 [CIVIC-703] [CIVIC-704] Listing component - Card theme and background fix
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/13.component.listing.inc
  docroot/themes/contrib/civictheme/includes/views.inc
Labels: Needs review

#501 [CIVIC-702] Fixed date missing in Promo Card with Event CT.
  docroot/themes/contrib/civictheme/includes/cards.inc
Labels: Needs review
