Repository civictheme/monorepo-drupal, pull requests merged in 2022-05, with the labels that each got.

#407 [CIVIC-454] Updated subject card component.
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_card_subject.field_c_p_image.yml
  tests/behat/features/paragraph.civictheme_card_subject.fields.feature
Labels: Needs review

#410 [ONI-610] Fixed mobile layout and alignment.
  docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/content/content-layout--single-column-contained.twig
  docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/content/content.twig
Labels: Needs review

#409 [CIVIC-575] Added side navigation spacing.
  docroot/themes/contrib/civictheme/civictheme-library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/side-navigation/side-navigation.scss
  docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/side-navigation/side-navigation.twig
Labels: Needs review

#406 [CIVIC-587] Fixed date styling on Promo card.
  docroot/themes/contrib/civictheme/civictheme-library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme-library/components/02-molecules/promo-card/promo-card.scss
Labels: Needs review

#405 [CIVIC-582] Changed "Card task" to "Task card".
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_card_task.yml
  docroot/themes/contrib/civictheme/includes/card_task.inc
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-card-task.html.twig
  tests/behat/features/content_type.civictheme_page.view.feature
  tests/behat/features/paragraph.civictheme_card_container.fields.feature
  tests/behat/features/paragraph.civictheme_card_task.fields.feature
Labels: Requires more work

#411 [CIVIC-448] Add headings to tables added via WYSIWYG.
  docroot/themes/contrib/civictheme/civictheme-library/components/01-atoms/table/table.js
  docroot/themes/contrib/civictheme/civictheme-library/components/01-atoms/table/table.stories.js
Labels: Needs review

#413 Add support for safari 13.
  docroot/themes/contrib/civictheme/civictheme-library/components/00-base/responsive/responsive.js
Labels: Ready to be merged

#408 [CIVIC-608] Content component behat test.
  composer.lock
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_next_step.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_next_step.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_icon.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_link.yml
  docroot/themes/contrib/civictheme/includes/next_step.inc
  tests/behat/features/paragraph.civictheme_accordion.view.feature
  tests/behat/features/paragraph.civictheme_attachment.view.feature
  tests/behat/features/paragraph.civictheme_callout.view.feature
  tests/behat/features/paragraph.civictheme_card_container.view.feature
  tests/behat/features/paragraph.civictheme_content.view.feature
  tests/behat/features/paragraph.civictheme_iframe.view.feature
  tests/behat/features/paragraph.civictheme_map.view.feature
  tests/behat/features/paragraph.civictheme_next_step.fields.feature
  tests/behat/features/paragraph.civictheme_next_step.view.feature
  tests/behat/features/paragraph.civictheme_slider.view.feature
  tests/behat/features/paragraph.civictheme_webform.view.feature
  tests/behat/fixtures/test_pdf.pdf
Labels: Needs review, Question

#412 [CIVIC-609] CS demo generation module.
  docroot/modules/custom/cs_core/cs_core.info.yml
  docroot/modules/custom/cs_demo/assets/dummy.doc
  docroot/modules/custom/cs_demo/assets/dummy.docx
  docroot/modules/custom/cs_demo/assets/dummy.gif
  docroot/modules/custom/cs_demo/assets/dummy.jpeg
  docroot/modules/custom/cs_demo/assets/dummy.jpg
  docroot/modules/custom/cs_demo/assets/dummy.mp3
  docroot/modules/custom/cs_demo/assets/dummy.mp4
  docroot/modules/custom/cs_demo/assets/dummy.pdf
  docroot/modules/custom/cs_demo/assets/dummy.png
  docroot/modules/custom/cs_demo/assets/dummy.svg
  docroot/modules/custom/cs_demo/assets/dummy.xls
  docroot/modules/custom/cs_demo/assets/dummy.xlsx
  docroot/modules/custom/cs_demo/content/media/civictheme_document.inc
  docroot/modules/custom/cs_demo/content/media/civictheme_icon.inc
  docroot/modules/custom/cs_demo/content/media/civictheme_image.inc
  docroot/modules/custom/cs_demo/content/node/civictheme_page.inc
  docroot/modules/custom/cs_demo/content/node/helper.inc
  docroot/modules/custom/cs_demo/content/taxonomy_term/topics.inc
  docroot/modules/custom/cs_demo/content/user/user.inc
  docroot/modules/custom/cs_demo/cs_demo.info.yml
  docroot/modules/custom/cs_demo/cs_demo.install
  docroot/modules/custom/cs_demo/cs_demo.links.menu.yml
  docroot/modules/custom/cs_demo/cs_demo.module
  docroot/modules/custom/cs_demo/cs_demo.permissions.yml
  docroot/modules/custom/cs_demo/cs_demo.routing.yml
  docroot/modules/custom/cs_demo/cs_demo.services.yml
  docroot/modules/custom/cs_demo/drush.services.yml
  docroot/modules/custom/cs_demo/src/Commands/CsDemoCommands.php
  docroot/modules/custom/cs_demo/src/CsDemoBatch.php
  docroot/modules/custom/cs_demo/src/CsDemoBatchService.php
  docroot/modules/custom/cs_demo/src/CsDemoHelper.php
  docroot/modules/custom/cs_demo/src/CsDemoRandom.php
  docroot/modules/custom/cs_demo/src/CsDemoRepository.php
  docroot/modules/custom/cs_demo/src/CsDemoTrait.php
  docroot/modules/custom/cs_demo/src/CsDemoVariationTrait.php
  docroot/modules/custom/cs_demo/src/CsGenerator.php
  docroot/modules/custom/cs_demo/src/Form/CsDemoForm.php
  docroot/modules/custom/cs_demo/src/Plugin/ConfigFilter/CsDemoIgnoreFilter.php
  scripts/custom/drupal-install-site-1-enable-modules.sh
Labels: DO NOT MERGE, Needs review, Question

#417 [CIVIC-569] Added theme styling to listing title.
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-listing.html.twig
Labels: Needs review

#419 [CIVIC-616] Added theme field to Listing component.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_theme.yml
  tests/behat/features/paragraph.civictheme_listing.fields.feature
Labels: Needs review

#421 [CIVIC-624] Fixed bug showing active underlined links and extra spacing for item without dropdown.
  docroot/themes/contrib/civictheme/civictheme-library/components/03-organisms/primary-navigation/primary-navigation.scss
Labels: Needs review

#420 [CIVIC-611] Updated Listing component.
  docroot/modules/custom/cs_demo/content/node/civictheme_page.inc
  docroot/modules/custom/cs_demo/src/CsDemoTrait.php
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_hide_count.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_show_pager.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_hide_count.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_show_pager.yml
  docroot/themes/contrib/civictheme/config/install/views.view.civictheme_listing.yml
  docroot/themes/contrib/civictheme/includes/listing.inc
  tests/behat/features/paragraph.civictheme_listing.fields.feature
Labels: Ready to be merged

#423 [CIVIC-622] Fixed Skip Link not having a URL.
  docroot/themes/contrib/civictheme/civictheme-library/components/04-templates/page/page.twig
  docroot/themes/contrib/civictheme/templates/layout/html.html.twig
Labels: Needs review

#428 Added RenovateBot configuration.
  .circleci/config.yml
  CI.md
Labels: DO NOT MERGE, Do not review

#429 Increased CI resource class to large.
  .circleci/config.yml
Labels: DO NOT MERGE, Do not review

#427 Enabled GitHub deployment notifications.
  .lagoon.yml
Labels: Do not review

#426 [CIVIC-633] Fixed Alert dismissal.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
Labels: DO NOT MERGE, Needs review, Question

#416 Add theme, vertical space, with background to listing component.
  docroot/themes/contrib/civictheme/civictheme.api.php
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_create_subtheme.php
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/large-filter/large-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.twig
  docroot/themes/contrib/civictheme/civictheme_starter_kit/civictheme_starter_kit.theme
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_background.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_card_theme.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_card_theme.yml
  docroot/themes/contrib/civictheme/includes/cards.inc
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/listing.inc
  docroot/themes/contrib/civictheme/includes/pager.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  docroot/themes/contrib/civictheme/templates/form/input--submit.html.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-listing.html.twig
  docroot/themes/contrib/civictheme/templates/views/views-exposed-form.html.twig
  docroot/themes/contrib/civictheme/templates/views/views-view-grid.html.twig
  docroot/themes/contrib/civictheme/templates/views/views-view.html.twig
  tests/behat/features/paragraph.civictheme_iframe.view.feature
  tests/behat/features/paragraph.civictheme_listing.fields.feature
  tests/behat/features/paragraph.civictheme_listing.view.feature
Labels: Needs review
