Repository civictheme/monorepo-drupal, pull requests merged in 2022-08, with the labels that each got.

#541 [CIVIC-664] Updated starter kit theme script to remove example component.
  docroot/themes/contrib/civictheme/civictheme_create_subtheme.php
  tests/phpunit/unit/CivicthemeCreateSubthemeScriptUnitTest.php
Labels: Ready to be merged

#540 [CIVIC-956] Added allowing to select card type in card container in Storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/logo/logo.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/service-card/service-card.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/card-container/card-container.stories.js
  docroot/themes/contrib/civictheme/theme-settings.php
Labels: Needs review

#544 [CIVIC-695] Added site section name to the content.
  docroot/modules/custom/cs_generated_content/generated_content/taxonomy_term/civictheme_site_sections.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.taxonomy_term.civictheme_site_sections.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_site_section.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_site_section.yml
  docroot/themes/contrib/civictheme/config/install/taxonomy.vocabulary.civictheme_site_sections.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  scripts/theme_excluded_configs.txt
  tests/behat/features/content_type.civictheme_page.fields.feature
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Needs review

#542 [CIVIC-736] Added Print mixins and added to related component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_print.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/back-to-top/back-to-top.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/search/search.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/content/content.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/primary-navigation/primary-navigation.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/secondary-navigation/secondary-navigation.scss
  docroot/themes/contrib/civictheme/includes/form.inc
Labels: Needs review

#549 Update All Contrib
  composer.lock
Labels: dependencies

#553 [CIVIC-613] Updated Background component to use semi-transparent theme-independent images.
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_1.png
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_2.png
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_dark_1.jpg
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_dark_2.jpg
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_light_1.jpg
  docroot/themes/contrib/civictheme/assets/backgrounds/civictheme_background_light_2.jpg
  docroot/themes/contrib/civictheme/civictheme.provision.inc
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_1.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_2.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_3.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_4.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_5.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_6.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_7.png
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_1.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_2.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_3.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_4.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_5.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_6.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_dark_7.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_1.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_2.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_3.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_4.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_5.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_6.jpg
  docroot/themes/contrib/civictheme/civictheme_library/assets/backgrounds/civictheme_background_light_7.jpg
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_background.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/background/background.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/background/background.stories.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/background/background.utils.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.stories.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_1.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_2.png
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_dark_1.jpg
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_dark_2.jpg
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_light_1.jpg
  docroot/themes/contrib/civictheme/civictheme_starter_kit/assets/backgrounds/civictheme_starter_kit_background_light_2.jpg
Labels: Ready to be merged

#555 [CIVIC] Added support for empty string as alt attribute value on image component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/image/image.twig
Labels: Needs review

#550 [CIVIC-359] Updated Listing limit fields.
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_listing.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_limit_type.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_listing.field_c_p_listing_limit.yml
  docroot/themes/contrib/civictheme/includes/listing.inc
  tests/behat/features/paragraph.civictheme_listing.fields.feature
  tests/behat/features/paragraph.civictheme_listing.view.feature
Labels: Needs review

#557 [CIVIC-961] Added font smoothing.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/fonts/_index.scss
Labels: Ready to be merged

#563 Update All Contrib
  composer.lock
Labels: dependencies

#556 [CIVIC-959] Added external link icons for external links.
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/config/install/civictheme.settings.yml
  docroot/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
  docroot/themes/contrib/civictheme/config/schema/civictheme.schema.yml
  docroot/themes/contrib/civictheme/includes/accordion.inc
  docroot/themes/contrib/civictheme/includes/content.inc
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/process.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeHtmlLinkUnitTest.php
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeParseAttributesUnitTest.php
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeUtilitiesUnitTest.php
  docroot/themes/contrib/civictheme/theme-settings.php
  tests/behat/features/links.feature
  tests/behat/features/theme.settings.feature
Labels: Ready to be merged

#565 [CIVIC-963] Added cache tags for exposed filters to avoid exposed block cache.
  docroot/themes/contrib/civictheme/includes/form.inc
  tests/behat/features/view.civictheme_listing_examples.feature
Labels: Needs review

#568 [CIVIC-960] Updated breadcrumb to show actual parent value on mobile.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/breadcrumb/breadcrumb.twig
  tests/behat/features/breadcrumb.view.feature
Labels: Needs review

#567 Fixed external links not always being replaced.
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/theme-settings.php
Labels: Ready to be merged

#569 [CIVIC-957] Added Size field to Navigation card paragraph.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_navigation_card.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_navigation_card.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_navigation_card.field_c_p_size.yml
  docroot/themes/contrib/civictheme/includes/navigation_card.inc
  tests/behat/features/paragraph.civictheme_navigation_card.fields.feature
Labels: Needs review

#566 [CIVIC-965] Added uploading of logo images in theme settings.
  docroot/themes/contrib/civictheme/theme-settings.php
  tests/behat/features/theme.settings.feature
  tests/behat/fixtures/test_image_logo_dark_desktop.jpg
  tests/behat/fixtures/test_image_logo_dark_mobile.jpg
  tests/behat/fixtures/test_image_logo_light_desktop.jpg
  tests/behat/fixtures/test_image_logo_light_mobile.jpg
Labels: Ready to be merged

#570 [CIVIC-966] Applied Core Patches to fix Correct vertical tab does not focus on form validation && drupal_phpunit_find_extension_directories() uses infinite recursion ⇒ more directories = slower tests
  composer.json
  composer.lock
Labels: Needs review

#571 [CIVIC-968] Added Linkit profile for content and media.
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/editor.editor.civictheme_rich_text.yml
  docroot/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
  docroot/themes/contrib/civictheme/config/install/user.role.civictheme_content_approver.yml
  docroot/themes/contrib/civictheme/config/install/user.role.civictheme_content_author.yml
  docroot/themes/contrib/civictheme/config/install/user.role.civictheme_site_administrator.yml
  docroot/themes/contrib/civictheme/config/optional/linkit.linkit_profile.civictheme.yml
  tests/behat/features/linkit.feature
Labels: Needs review

#574 [CIVIC-969] Updated to the latest dependencies.
  composer.json
  composer.lock
Labels: Needs review

#576 [CIVIC-972] Removed unused redis service.
  composer.json
  composer.lock
  docker-compose.yml
Labels: DO NOT MERGE, Do not review

#583 [CIVIC-975] Added site section class to body element.
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/includes/html.inc
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Needs review

#582 [CIVIC-974] Fixed tabs order.
  docroot/themes/contrib/civictheme/includes/local_tasks.inc
Labels: Needs review

#581 [CIVIC-572] Fixed mobile Side Navigation menu collapsing on grand-parents.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/menu/menu.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/mobile-navigation/mobile-navigation-menu.twig
Labels: Needs review

#578 [CIVIC-976] Fixed missing menu block values added on build of a child theme.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/b7f36176-620f-4178-aadd-9b448c610986.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/b7f36176-620f-4178-aadd-9b448c610986.yml
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.block_content.civictheme_mobile_navigation.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.block_content.civictheme_mobile_navigation.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_mobile_navigation.field_c_b_bottom.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_mobile_navigation.field_c_b_top.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_bottom.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.block_content.field_c_b_top.yml
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
  docroot/themes/contrib/civictheme/theme-settings.provision.inc
  tests/behat/features/block_type.civictheme_mobile_navigation.fields.feature
Labels: Needs review

#585 [CIVIC-625] Fixed builds failing on missing layout column plugin.
  scripts/drevops/drupal-install-site.sh
Labels: Needs review

#588 [CIVIC-981] Added Content link component
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/ckeditor-content/ckeditor-content.stories.js
Labels: Needs review

#591 [CIVIC-771] Updated storybook button component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.twig
Labels: Needs review

#592 [CIVIC-765] Updated heading storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/heading/heading.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/heading/heading.stories.js
Labels: Needs review

#596 [CIVIC-792] Renamed component Label to Field label and updated props,…
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/base.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-label/field-label.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-label/field-label.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-label/field-label.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/label/label.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/label/label.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/form-element/form-element.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/password-indicator/password-indicator.stories.twig
  docroot/themes/contrib/civictheme/templates/form/form-element-label.html.twig
Labels: Needs review

#603 [CIVIC-810] Updated Checkbox components in Storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.twig
Labels: Needs review

#601 [CIVIC-786] Updated Table component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/table/table.twig
Labels: Ready to be merged

#600 [CIVIC-789] Updated Tag component.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/tag/tag.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
Labels: Ready to be merged

#604 [CIVIC-989] Updated to use typography.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-label/field-label.scss
Labels: Ready to be merged

#608 [CIVIC-991] Fixed incorrect external link icons.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
Labels: Ready to be merged

#607 [CIVIC-990] Fixed missing Corporate.civictheme.io - Default content - Social icons.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/5c0ad15f-3e9c-4eeb-8525-7a064b06fc58.yml
Labels: Ready to be merged
