Repository civictheme/monorepo-drupal, pull requests merged in 2022-10, with the labels that each got.

#774 Update All Contrib
  composer.lock
Labels: dependencies

#775 [CIVIC-843] Fixed navigation card styles.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/navigation-card/navigation-card.twig
Labels: Needs review

#776 [CIVIC-855] Fixed Subject card styles.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/subject-card/subject-card.twig
Labels: Ready to be merged

#780 [CIVIC-1042] Updated Next step component design.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/next-steps/next-steps.scss
Labels: Ready to be merged

#779 [CIVIC-1100] Updated Drupal attachment paragraph.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/06.component.attachment.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_attachment.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_attachment.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_attachment.field_c_p_icon.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_attachment.field_c_p_image.yml
  tests/behat/features/paragraph.civictheme_attachment.fields.feature
  tests/behat/features/paragraph.civictheme_attachment.view.feature
Labels: Requires more work

#778 [CIVIC-1077] Fixed TOC width on mobile.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
Labels: Requires more work

#782 [CIVIC-1070] Updated pager component, fixed link styles.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
  tests/behat/features/pagination.view.feature
Labels: Needs review

#784 [CIVIC-1096] Fixed Event card design.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/event-card/event-card.twig
Labels: Needs review

#786 [CIVIC-1088] Removed image field from Next step component.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/10.component.next_step.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_next_step.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_next_step.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_next_step.field_c_p_image.yml
  tests/behat/features/paragraph.civictheme_next_step.fields.feature
Labels: Needs review

#785 [CIVIC-1081] Fixed Quote component design.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
Labels: Needs review

#787 [CIVIC-849] Updated publication card design.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.twig
  docroot/themes/contrib/civictheme/includes/publication_card.inc
Labels: Ready to be merged

#791 Update All Contrib
  composer.lock
Labels: dependencies

#789 [CIVIC-1092] Breadcrumb title fix.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/breadcrumb/breadcrumb.scss
Labels: Needs review

#792 Update All Contrib
  composer.json
  composer.lock
Labels: dependencies

#795 [CIVIC-1069] Fixed menu external link design.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/navigation/navigation.scss
Labels: Needs review

#794 [CIVIC-918] Fixed list component properties.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.stories.js
Labels: Ready to be merged

#801 [CIVIC] Fix typo on slider.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss
Labels: Needs review

#800 [CIVIC-945] Added Campaign component to Storybook.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.stories.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/campaign/campaign.twig
Labels: Needs review

#805 Updated default content yml.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
Labels: Needs review

#803 [CIVIC-1117] Added support for CSS variables.
  docroot/themes/contrib/civictheme/.storybook/components_css.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/.storybook/css.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.base.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_color.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_component.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_index.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_map.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/mixins/_string.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/field-description/field-description.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/heading/heading.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/iframe/iframe.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/label/label.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/banner/banner.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/promo/promo.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/skip-link/skip-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/slider/slider.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/style.css_variables.scss
  docroot/themes/contrib/civictheme/civictheme_library/package.json
  docroot/themes/contrib/civictheme/civictheme_library/webpack/css.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.storybook/components_css.stories.js
  docroot/themes/contrib/civictheme/civictheme_starter_kit/webpack/components_css.js
  docroot/themes/contrib/civictheme/webpack/components_css.js
Labels: DO NOT MERGE, Do not review

#802 [CIVIC-1106] Fixed site section CSS.
  docroot/themes/contrib/civictheme/includes/html.inc
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Needs review

#807 [CIVIC-1100] Updated Attachment component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
  docroot/themes/contrib/civictheme/includes/attachment.inc
Labels: Needs review

#806 Update All Contrib
  composer.lock
Labels: Ready to be merged, dependencies

#804 [CIVIC-919] Fixed multiple components.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/group-filter/group-filter.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/promo-card/promo-card.twig
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
Labels: Ready to be merged

#811 [CIVIC-1118] Updated color mapper looks.
  docroot/themes/contrib/civictheme/civictheme.libraries.yml
  docroot/themes/contrib/civictheme/theme-settings/civictheme.theme-settings.colors.css
  docroot/themes/contrib/civictheme/theme-settings/civictheme.theme-settings.css
Labels: Needs review

#809 [CIVIC-916] Updated Manual list component and removed Task card.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/617c7fad-dfb9-481a-95f0-6774f5471aca.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/32e84de2-85db-425c-88e9-b311ba69e352.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/3b6641e0-cd4c-4649-a480-6c017fffb102.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/5c23a0bd-3ee8-4608-bdec-b396f0be3c7d.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/a15b6d80-d397-466b-be74-4573eba1b6b2.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/c0e41832-051b-4570-ab91-8b47c1c8d75d.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/e6cb58d5-605b-4013-a682-30fec3307c74.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/e7ae2692-4f90-4bd9-9f3d-89dfe3adf88e.yml
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/15.component.manual_list.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/button/button.scss
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_manual_list.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_task_card.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_manual_list.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_task_card.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_component_block.field_c_b_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.block_content.civictheme_social_links.field_c_b_social_icons.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_event.field_c_n_attachments.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_event.field_c_n_location.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_components_bott.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_components.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_accordion.field_c_p_panels.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_manual_list.field_c_p_list_items.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_publication_card.field_c_p_theme.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_slider.field_c_p_slides.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_task_card.field_c_p_icon.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_task_card.field_c_p_link.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_task_card.field_c_p_summary.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_task_card.field_c_p_title.yml
  docroot/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_task_card.yml
  docroot/themes/contrib/civictheme/includes/manual_list.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/task_card.inc
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-manual-list.html.twig
  tests/behat/features/content_type.civictheme_page.view.feature
  tests/behat/features/paragraph.civictheme_manual_list.fields.feature
  tests/behat/features/paragraph.civictheme_manual_list.view.feature
  tests/behat/features/paragraph.civictheme_publication_card.fields.feature
  tests/behat/features/paragraph.civictheme_task_card.fields.feature
Labels: Needs review

#815 [CIVIC-1119] Added unit test for color classes.
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeColorUtilityUnitTest.php
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeUtilityUnitTest.php
Labels: Needs review

#821 [CIVIC-1122] Fixed automated list pages 500 error.
  docroot/themes/contrib/civictheme/includes/views.inc
Labels: Needs review

#820 Update dependency drush/drush to v11.3.1
  composer.lock
Labels: dependencies

#816 [CIVIC] Fix list typo in Drupal template.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/list/list.twig
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-manual-list.html.twig
Labels: Needs review

#818 Update All Contrib
  composer.lock
Labels: dependencies

#822 Fixed missing plain text plugin error logs.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/0ba446a2-c1ce-4c8e-a20d-0d9ae5949aca.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/1accbc91-68c8-4a86-a973-b7120ce05c9c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/2cb01445-7f3f-4aca-9451-6d26a6032100.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/4d273ca8-0889-4e43-8edd-73fcb4ed8340.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/5750f380-5fb2-484a-8f78-9e1fa1749c32.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/583e8b18-8156-415c-a80e-4dbf564d5f99.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/5a7cc060-cdf5-4097-8dce-15a0c7270f98.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/60ac1244-9ada-43d3-a534-4e54086cc29e.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/78160c95-cb6d-4321-9aba-2118aff8fc59.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/91452662-e67a-4c74-aabc-bf37d25d43d8.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/a0539fd0-ef51-47c9-a47b-e08199052f1e.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/afb3e47d-409f-47c9-b5cc-0bbb00531e19.yml
Labels: Needs review

#823 [CIVIC-1017] Fixed mixed level symbols issue.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/typography/_index.scss
Labels: Ready to be merged

#824 Update dependency drush/drush to v11.3.2
  composer.lock
Labels: dependencies

#825 [CIVIC-1123] Fixed color stylesheet generation to correclty handle active theme prefix.
  docroot/themes/contrib/civictheme/civictheme.libraries.yml
  docroot/themes/contrib/civictheme/civictheme.theme
  tests/behat/features/theme.settings.color.feature
Labels: Needs review

#799 [CIVIC-1105] Add Merlin UI migration connector.
  composer.d10.json
  composer.d10.lock
  composer.json
  composer.lock
  docroot/modules/custom/civictheme_govcms/composer.json
  docroot/modules/custom/civictheme_migrate/README.md
  docroot/modules/custom/civictheme_migrate/assets/migrations/migrate_plus.migration.civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/assets/schema/civictheme_page.json
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.info.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.links.menu.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.module
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.routing.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.services.yml
  docroot/modules/custom/civictheme_migrate/composer.json
  docroot/modules/custom/civictheme_migrate/config/install/civictheme_migrate.settings.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration_group.civictheme_migrate.yml
  docroot/modules/custom/civictheme_migrate/config/schema/civictheme_migration.schema.yml
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateManager.php
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateValidator.php
  docroot/modules/custom/civictheme_migrate/src/Form/CivicthemeMigrateConfigurationForm.php
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_no_id_key.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_no_title_key.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/invalid_not_array_of_objects.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/valid_multiple_element.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/migration_source_json/valid_single_element.json
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/CivicthemeMigrateValidatorTest.php
  docroot/themes/contrib/civictheme/.eslintrc.yml
  docroot/themes/contrib/civictheme/civictheme_starter_kit/.eslintrc.yml
  scripts/custom/drupal-install-site-3-provision-content.sh
  tests/behat/features/migrate.feature
  tests/behat/fixtures/civictheme_migrate.invalid_json_1.json
  tests/behat/fixtures/civictheme_migrate.page_content_1.json
  tests/behat/fixtures/civictheme_migrate.page_content_2.json
Labels: Ready to be merged

#826 [CIVIC-1123] Added behat test to check for color updation.
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/theme.settings.color.feature
Labels: Needs review

#829 [CIVIC-1089] Removed extra margin from alert component in drupal FE.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/alert/alert.twig
Labels: Needs review

#828 [CIVIC-1099] Updated attachment storybook component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/attachment/attachment.twig
  docroot/themes/contrib/civictheme/includes/attachment.inc
Labels: Needs review

#831 [CIVIC-1131] Removed "Show filters" checkbox from Automated list.
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/5508dc51-1cf8-4577-9038-b572fbd698ae.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/5c0ad15f-3e9c-4eeb-8525-7a064b06fc58.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/file/d415ede9-ef24-420d-bb6d-7ccfc40b4694.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/media/26820d38-aabc-4c1d-a6df-09fa62a3fe8a.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/node/51efffb7-e00c-48ee-a5a4-8eabb7c9e903.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/5508dc51-1cf8-4577-9038-b572fbd698ae.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/5c0ad15f-3e9c-4eeb-8525-7a064b06fc58.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/d7098a8c-3ba3-48f7-bc0c-5787ebaa0427.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/45b59dbe-af6c-4b71-b12a-a79b39ee140c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/46827268-e7c7-4ace-92be-bd16d931f48d.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/node/db8e6781-f356-497d-9aba-ef0994b6268c.yml
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_automated_list.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_manual_list.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_automated_list.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_filters_exp.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_show_filters.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_list_show_filters.yml
  docroot/themes/contrib/civictheme/includes/automated_list.inc
  docroot/themes/contrib/civictheme/includes/map.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/paragraph.civictheme_automated_list.fields.feature
  tests/behat/features/paragraph.civictheme_automated_list.view.feature
Labels: Ready to be merged
