Repository civictheme/monorepo-drupal, pull requests merged in 2022-07, with the labels that each got.

#508 [CIVIC-713] Fixed Callout CTA when without link text.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
Labels: Needs review

#509 [CIVIC-711] Fixed Reference content does not render in the Slider component
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/templates/content/node--civictheme-slider-slide.html.twig
Labels: Needs review

#510 [CIVIC-693] Hide breadcrumb option in banner.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/04.banner.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_hide_breadcrumb.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_banner_hide_breadcrumb.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  tests/behat/features/content_type.civictheme_page.fields.feature
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Needs review

#511 [CIVIC-694] Banner title field implementation.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/04.banner.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_banner_title.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_banner_title.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  tests/behat/features/content_type.civictheme_page.fields.feature
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Ready to be merged

#507 [CIVIC-709] Fixed broken exposed form of Views with CivicTheme
  docroot/modules/custom/cs_core/config/install/views.view.civictheme_test.yml
  docroot/modules/custom/cs_core/config/optional/block.block.exposedformcivictheme_testpage_civictheme.yml
  docroot/modules/custom/cs_core/config/optional/block.block.exposedformcivictheme_testpage_civictheme_demo.yml
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/listing.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/civictheme_test.view.feature
Labels: Ready to be merged

#514 [CIVIC-684] Fixed ‘Link’ menu field does not get updated immediately on mobile
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
Labels: Needs review

#512 [CIVIC-708] Fixed Publication Card content cut-off when column count is more.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/publication-card/publication-card.scss
Labels: Needs review

#515 [CIVIC-671] Fixed Accordion Dark colour does not apply to content inner region.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/accordion/accordion.scss
Labels: Ready to be merged

#517 [CIVIC] Fixed video player typo.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig
Labels: Needs review

#519 [CIVIC-721] Fixed content fields to allow tokens and filters
  docroot/themes/contrib/civictheme/includes/accordion.inc
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  tests/behat/features/media.image.view.feature
Labels: Needs review

#521 Update All Contrib
  composer.lock
Labels: dependencies

#522 [CIVIC-715] Added Webform component to Storybook and add theme/spacing/background.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/14.component.webform.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/webform/webform.twig
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_webform.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_webform.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_background.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_space.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_webform.field_c_p_theme.yml
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-webform.html.twig
  tests/behat/features/paragraph.civictheme_webform.fields.feature
  tests/behat/features/paragraph.civictheme_webform.view.feature
Labels: Needs review

#523 [CIVIC-732] Added field existence and value check helper.
  docroot/themes/contrib/civictheme/includes/attachment.inc
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/callout.inc
  docroot/themes/contrib/civictheme/includes/card_container.inc
  docroot/themes/contrib/civictheme/includes/cards.inc
  docroot/themes/contrib/civictheme/includes/event_card.inc
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/iframe.inc
  docroot/themes/contrib/civictheme/includes/map.inc
  docroot/themes/contrib/civictheme/includes/media.inc
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
  docroot/themes/contrib/civictheme/includes/navigation_card.inc
  docroot/themes/contrib/civictheme/includes/next_step.inc
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/promo.inc
  docroot/themes/contrib/civictheme/includes/promo_card.inc
  docroot/themes/contrib/civictheme/includes/publication_card.inc
  docroot/themes/contrib/civictheme/includes/quick_links.inc
  docroot/themes/contrib/civictheme/includes/service_card.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  docroot/themes/contrib/civictheme/includes/social_links.inc
  docroot/themes/contrib/civictheme/includes/subject_card.inc
  docroot/themes/contrib/civictheme/includes/task_card.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
Labels: Needs review

#524 [CIVIC-732] Added field existence and value check helper.
  docroot/themes/contrib/civictheme/includes/accordion.inc
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/cards.inc
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/iframe.inc
  docroot/themes/contrib/civictheme/includes/map.inc
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
  docroot/themes/contrib/civictheme/includes/next_step.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/promo.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  docroot/themes/contrib/civictheme/includes/social_links.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
Labels: Ready to be merged

#526 [CIVIC-731] Fixed Card Theme being applied inconsistent in the Listing component
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/paragraph.civictheme_listing.view.feature
Labels: Needs review

#518 [CIVIC-720] Fixed Duplicated content blocks issue when default content is enabled.
  docroot/modules/custom/civictheme_content/civictheme_content.install
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/013da091-dbf4-4e0d-8c57-11e0561b6bbe.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/2fc1a967-a188-48ed-ab3a-f455c91ff8db.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/5c0ad15f-3e9c-4eeb-8525-7a064b06fc58.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/7cf65f98-cbae-4e9d-b6ea-7d6d1c437c1c.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/b674b616-0cd4-4484-b07b-a5d766b77764.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/b7f36176-620f-4178-aadd-9b448c610986.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/content/block_content/fdc00188-bef1-4974-8bce-9875bb158580.yml
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/content/block_content/286ff750-a9a9-423a-8a4e-515f79fc0a8f.yml
  docroot/themes/contrib/civictheme/civictheme.provision.inc
Labels: Requires more work

#505 [CIVIC-690] Styled Drupal elements without blocks.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/footer/footer.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/header/header.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/listing/listing.twig
  docroot/themes/contrib/civictheme/templates/views/views-view.html.twig
Labels: Needs review

#530 Update dependency govcms/govcms to v2.17.0
  composer.json
  composer.lock
Labels: Ready to be merged, dependencies

#529 [CIVIC-732] Added civictheme_get_field_value.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/callout/callout.twig
  docroot/themes/contrib/civictheme/includes/accordion.inc
  docroot/themes/contrib/civictheme/includes/attachment.inc
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/callout.inc
  docroot/themes/contrib/civictheme/includes/card_container.inc
  docroot/themes/contrib/civictheme/includes/cards.inc
  docroot/themes/contrib/civictheme/includes/content.inc
  docroot/themes/contrib/civictheme/includes/event_card.inc
  docroot/themes/contrib/civictheme/includes/iframe.inc
  docroot/themes/contrib/civictheme/includes/listing.inc
  docroot/themes/contrib/civictheme/includes/map.inc
  docroot/themes/contrib/civictheme/includes/media.inc
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
  docroot/themes/contrib/civictheme/includes/navigation_card.inc
  docroot/themes/contrib/civictheme/includes/next_step.inc
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/promo.inc
  docroot/themes/contrib/civictheme/includes/promo_card.inc
  docroot/themes/contrib/civictheme/includes/publication_card.inc
  docroot/themes/contrib/civictheme/includes/quick_links.inc
  docroot/themes/contrib/civictheme/includes/search.inc
  docroot/themes/contrib/civictheme/includes/service_card.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  docroot/themes/contrib/civictheme/includes/social_links.inc
  docroot/themes/contrib/civictheme/includes/subject_card.inc
  docroot/themes/contrib/civictheme/includes/task_card.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  tests/behat/features/content_type.civictheme_alert.view.feature
  tests/behat/features/paragraph.civictheme_event_card.view.feature
Labels: Needs review

#531 [CIVIC-737] Updated Reference slide to have a theme field
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_slider_slide_ref.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_slider_slide_ref.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_slider_slide_ref.field_c_p_image_position.yml
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_slider_slide_ref.field_c_p_theme.yml
  docroot/themes/contrib/civictheme/includes/node.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  docroot/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-slider-slide-ref.html.twig
  tests/behat/features/paragraph.civictheme_slider_slide_ref.fields.feature
Labels: Ready to be merged

#533 [CIVIC] Fixed typo on video component.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/video-player/video-player.twig
Labels: Needs review

#534 Update dependency drupal/core-dev to v9.4.3
  composer.lock
Labels: dependencies

#532 [CIVIC-734] Added PHPMD.
  .env
  composer.json
  composer.lock
  docroot/modules/custom/civictheme_content/modules/civictheme_content_corporate/civictheme_content_corporate.post_update.php
  docroot/modules/custom/civictheme_content/modules/civictheme_content_default/civictheme_content_default.post_update.php
  docroot/modules/custom/civictheme_content/src/Helper.php
  docroot/modules/custom/cs_core/src/Helper.php
  docroot/themes/contrib/civictheme/civictheme.provision.inc
  docroot/themes/contrib/civictheme/civictheme_create_subtheme.php
  docroot/themes/contrib/civictheme/civictheme_library/scripts/extract_css_colors_to_csv.php
  docroot/themes/contrib/civictheme/civictheme_starter_kit/scripts/update_config.php
  docroot/themes/contrib/civictheme/includes/attachment.inc
  docroot/themes/contrib/civictheme/includes/banner.inc
  docroot/themes/contrib/civictheme/includes/callout.inc
  docroot/themes/contrib/civictheme/includes/cards.inc
  docroot/themes/contrib/civictheme/includes/content.inc
  docroot/themes/contrib/civictheme/includes/filter.inc
  docroot/themes/contrib/civictheme/includes/form.inc
  docroot/themes/contrib/civictheme/includes/iframe.inc
  docroot/themes/contrib/civictheme/includes/listing.inc
  docroot/themes/contrib/civictheme/includes/media.inc
  docroot/themes/contrib/civictheme/includes/mobile_navigation.inc
  docroot/themes/contrib/civictheme/includes/pager.inc
  docroot/themes/contrib/civictheme/includes/paragraphs.inc
  docroot/themes/contrib/civictheme/includes/primary_navigation.inc
  docroot/themes/contrib/civictheme/includes/publication_card.inc
  docroot/themes/contrib/civictheme/includes/search.inc
  docroot/themes/contrib/civictheme/includes/secondary_navigation.inc
  docroot/themes/contrib/civictheme/includes/service_card.inc
  docroot/themes/contrib/civictheme/includes/slider.inc
  docroot/themes/contrib/civictheme/includes/system_branding.inc
  docroot/themes/contrib/civictheme/includes/utilities.inc
  docroot/themes/contrib/civictheme/includes/views.inc
  docroot/themes/contrib/civictheme/tests/src/Traits/CivicThemeTestHelperTrait.php
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicThemeExampleThemeUnitTest.php
  docroot/themes/contrib/civictheme/theme-settings.php
  scripts/drevops/lint.sh
  scripts/drevops/test.sh
Labels: Do not review

#537 Update dependency drupal/core-dev to v9.4.4
  composer.lock
Labels: dependencies

#536 [CIVIC-723] Added "Last updated date" as a custom date for Page content type.
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page.inc
  docroot/modules/custom/cs_generated_content/generated_content/node/civictheme_page_variations/03.general.inc
  docroot/themes/contrib/civictheme/civictheme.info.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_form_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_navigation_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_promo_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_slider_slide.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.civictheme_subject_card.yml
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_page.default.yml
  docroot/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_custom_last_updated.yml
  docroot/themes/contrib/civictheme/config/install/field.storage.node.field_c_n_custom_last_updated.yml
  docroot/themes/contrib/civictheme/includes/banner.inc
  tests/behat/features/content_type.civictheme_page.fields.feature
  tests/behat/features/content_type.civictheme_page.view.feature
Labels: Needs review
