Repository civictheme/monorepo-drupal, pull requests merged in 2023-04, with the labels that each got.

#1052 [CIVIC-1372] Fixed email extraction pattern.
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
Labels: State: Ready to be merged

#1050 Refactored civictheme_migrate module.
  docroot/modules/custom/civictheme_migrate/MAPPINGS.md
  docroot/modules/custom/civictheme_migrate/README.md
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/README.md
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/media_civictheme_image.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/node_civictheme_page.json
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.info.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.links.menu.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.module
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.routing.yml
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.services.yml
  docroot/modules/custom/civictheme_migrate/composer.json
  docroot/modules/custom/civictheme_migrate/config/install/civictheme_migrate.settings.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.media_civictheme_image.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.node_civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration_group.civictheme_migrate.yml
  docroot/modules/custom/civictheme_migrate/config/schema/civictheme_migrate.schema.yml
  docroot/modules/custom/civictheme_migrate/config/schema/civictheme_migration.schema.yml
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateManager.php
  docroot/modules/custom/civictheme_migrate/src/CivicthemeMigrateValidator.php
  docroot/modules/custom/civictheme_migrate/src/Form/CivicthemeMigrateConfigurationForm.php
  docroot/modules/custom/civictheme_migrate/src/Form/MigrationEditFormAlter.php
  docroot/modules/custom/civictheme_migrate/src/Form/SettingsForm.php
  docroot/modules/custom/civictheme_migrate/src/MigrationFileValidator.php
  docroot/modules/custom/civictheme_migrate/src/MigrationFileValidatorInterface.php
  docroot/modules/custom/civictheme_migrate/src/MigrationSchema.php
  docroot/modules/custom/civictheme_migrate/src/MigrationSchemaManager.php
  docroot/modules/custom/civictheme_migrate/src/MigrationSchemaManagerInterface.php
  docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/FileCopyDisposition.php
  docroot/modules/custom/civictheme_migrate/src/Utility.php
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_image_1.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_image_2.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.node_civictheme_page_1.json
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/MediaValidatorKernelTest.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/MigrationFileValidatorKernelTest.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/PageValidatorKernelTest.php
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/ValidatorKernelTestBase.php
  docroot/modules/custom/civictheme_migrate/tests/src/Unit/UtilityTest.php
  scripts/custom/drupal-install-site-3-provision-content.sh
  scripts/drevops/lint.sh
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/migrate.access.feature
  tests/behat/features/migrate.feature
  tests/behat/features/migrate.mappings.feature
  tests/behat/features/migrate.settings.feature
  tests/behat/fixtures/civictheme_migrate.invalid_json_1.json
  tests/behat/fixtures/civictheme_migrate.media_civictheme_image_1.json
  tests/behat/fixtures/civictheme_migrate.media_civictheme_image_2.json
  tests/behat/fixtures/civictheme_migrate.media_content_1.json
  tests/behat/fixtures/civictheme_migrate.media_content_2.json
  tests/behat/fixtures/civictheme_migrate.node_civictheme_page_1.json
  tests/behat/fixtures/civictheme_migrate.node_civictheme_page_2.json
  tests/behat/fixtures/civictheme_migrate.page_content_2.json
Labels: State: DO NOT MERGE, State: Do not review

#1058 Added support for github authentication during build.
  .docker/Dockerfile.cli
Labels: State: DO NOT MERGE, State: Do not review

#1037 [CIVIC-1032] Added migration mapping for Manual list and Accordion components, Topics vocabulary, Documents.
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/media_civictheme_document.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/node_civictheme_page.json
  docroot/modules/custom/civictheme_migrate/civictheme_migrate.services.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.media_civictheme_document.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.node_civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/src/ContentComponentFactory.php
  docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/ContentComponents.php
  docroot/modules/custom/civictheme_migrate/src/Utils/CivicthemeTrait.php
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_document_1.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.node_civictheme_page_components.json
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/MigrationFileValidatorKernelTest.php
  tests/behat/features/migrate.mappings.components.feature
  tests/behat/features/migrate.mappings.feature
  tests/behat/features/table.render.feature
  tests/behat/features/view.civictheme_automated_list_examples.feature
  tests/behat/fixtures/civictheme_migrate.media_civictheme_document_1.json
  tests/behat/fixtures/civictheme_migrate.node_civictheme_page_3.json
Labels: State: Needs review

#1061 Updated migration tests to rely on local files for remote assertions.
  docroot/modules/custom/civictheme_migrate/MAPPINGS.md
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/node_civictheme_page.json
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.node_civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_document_1.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_image_1.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.media_civictheme_image_2.json
  tests/behat/features/migrate.mappings.civictheme_page.feature
  tests/behat/features/migrate.mappings.components.feature
  tests/behat/fixtures/civictheme_migrate.media_civictheme_document_1.json
  tests/behat/fixtures/civictheme_migrate.media_civictheme_image_1.json
  tests/behat/fixtures/civictheme_migrate.media_civictheme_image_2.json
  tests/behat/fixtures/migrate/civictheme_migrate.media_civictheme_document_1.json
  tests/behat/fixtures/migrate/civictheme_migrate.media_civictheme_image_1.json
  tests/behat/fixtures/migrate/civictheme_migrate.media_civictheme_image_2.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_1.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_2.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_3.json
  tests/behat/fixtures/migrate/dummy1.jpg
  tests/behat/fixtures/migrate/dummy1.pdf
  tests/behat/fixtures/migrate/dummy1.txt
  tests/behat/fixtures/migrate/dummy2.jpg
  tests/behat/fixtures/migrate/dummy2.pdf
  tests/behat/fixtures/migrate/dummy2.txt
  tests/behat/fixtures/migrate/dummy3.jpg
  tests/behat/fixtures/migrate/dummy3.pdf
  tests/behat/fixtures/migrate/dummy3.txt
  tests/behat/fixtures/migrate/dummy4.jpg
  tests/behat/fixtures/migrate/dummy4.pdf
  tests/behat/fixtures/migrate/dummy4.txt
Labels: State: Needs review

#1063 [CIVIC-1130] Migrations - Menus: Primary, Secondary & Footer
  docroot/modules/custom/civictheme_migrate/MAPPINGS.md
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/media_civictheme_document.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/media_civictheme_image.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/menu_link_content_civictheme_footer.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/menu_link_content_civictheme_primary_navigation.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/menu_link_content_civictheme_secondary_navigation.json
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.media_civictheme_document.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.media_civictheme_image.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.menu_link_content_civictheme_footer.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.menu_link_content_civictheme_primary_navigation.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.menu_link_content_civictheme_secondary_navigation.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.node_civictheme_page.yml
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.menu_link_content_civictheme_footer.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.menu_link_content_civictheme_primary_navigation.json
  docroot/modules/custom/civictheme_migrate/tests/fixtures/civictheme_migrate.menu_link_content_civictheme_secondary_navigation.json
  docroot/modules/custom/civictheme_migrate/tests/src/Kernel/MigrationFileValidatorKernelTest.php
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/migrate.mappings.civictheme_page.feature
  tests/behat/features/migrate.mappings.components.attachments.feature
  tests/behat/features/migrate.mappings.components.feature
  tests/behat/features/migrate.mappings.menu.feature
  tests/behat/fixtures/migrate/civictheme_migrate.menu_link_content_civictheme_footer.json
  tests/behat/fixtures/migrate/civictheme_migrate.menu_link_content_civictheme_primary_navigation.json
  tests/behat/fixtures/migrate/civictheme_migrate.menu_link_content_civictheme_secondary_navigation.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_4.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_5.json
Labels: State: Needs review

#1064 [CIVIC-1362] Migrations mapping - Promo component
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/block_civictheme_block.json
  docroot/modules/custom/civictheme_migrate/assets/migration_schemas/block_content_civictheme_component_block.json
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.block_civictheme.yml
  docroot/modules/custom/civictheme_migrate/config/install/migrate_plus.migration.block_content_civictheme_component_block copy.yml
  docroot/modules/custom/civictheme_migrate/src/ContentComponentFactory.php
  docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/BlockPluginId.php
  docroot/modules/custom/civictheme_migrate/src/Plugin/migrate/process/BlockTheme.php
  docroot/modules/custom/civictheme_migrate/src/Utils/CivicthemeTrait.php
  tests/behat/bootstrap/FeatureContext.php
  tests/behat/features/migrate.mappings.components.promo.feature
  tests/behat/fixtures/migrate/civictheme_migrate.block_civictheme.json
  tests/behat/fixtures/migrate/civictheme_migrate.block_content_civictheme_component_block.json
  tests/behat/fixtures/migrate/civictheme_migrate.node_civictheme_page_6.json
Labels: State: Needs review
