Repository civictheme/monorepo-drupal, pull requests merged in 2023-01, with the labels that each got.

#930 [CIVIC-1296] Fixed toc jumping issue when clicked.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/table-of-contents/table-of-contents.scss
Labels: State: Needs review

#929 [CIVIC-1310] Updated ellipsis component to use single boolean.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.stories.js
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/pagination/pagination.twig
  docroot/themes/contrib/civictheme/includes/pager.inc
  docroot/themes/contrib/civictheme/templates/navigation/pager.html.twig
  docroot/themes/contrib/civictheme/templates/navigation/views-mini-pager.html.twig
  tests/behat/features/pagination.render.feature
Labels: State: Needs review

#918 [CIVIC-1239] Fixed ally Content Link component.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.twig
  docroot/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
Labels: State: Needs review

#933 [CIVIC-1239] Implemented icon for external links in content.
  docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/basic-content/basic-content.scss
  docroot/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
  docroot/themes/contrib/civictheme/includes/link.inc
  docroot/themes/contrib/civictheme/tests/src/Unit/CivicthemeHtmlLinkUnitTest.php
Labels: State: Needs review, State: Requires more work

#935 [CIVIC-1263] Updated message component.
  docroot/themes/contrib/civictheme/civictheme_library/components/03-organisms/message/message.twig
Labels: State: Ready to be merged

#940 [CIVIC-1256] Updated components to have aria-hidden set on SVG.
  docroot/themes/contrib/civictheme/civictheme_library/components/00-base/collapsible/collapsible.js
Labels: State: Needs review

#944 [CIVIC-1325] Updated Link and Content Link component’s CSS to use word-break to break content.
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/content-link/content-link.scss
  docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/link/link.scss
Labels: State: Needs review

#943 [CIVIC-1327] Updated Event card Image field to not be compulsory.
  docroot/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_event_card.field_c_p_image.yml
  tests/behat/features/paragraph.civictheme_event_card.fields.feature
Labels: State: Needs review

#942 [CIVIC-1332] Disabled the vertical spacing field value is rendering on Events page.
  docroot/themes/contrib/civictheme/config/install/core.entity_view_display.node.civictheme_event.default.yml
Labels: State: Needs review
