Repository civictheme/monorepo-drupal, pull requests merged in 2024-01, with the labels that each got.

#1190 Updated tzdata package.
  .docker/cli.dockerfile
  .docker/cli.onlytheme.dockerfile
  .docker/cli.sibling.dockerfile
  .docker/nginx-drupal.dockerfile
  .docker/php.dockerfile
Labels: State: DO NOT MERGE

#1193 Renamed custom scripts.
  .ahoy.yml
  .circleci/config.yml
  scripts/deploy-code-release.sh
  scripts/git-mirror.sh
  scripts/lint-spelling.sh
  scripts/lint.spelling.sh
  scripts/lint.theme-config.sh
  scripts/push.code.sh
  scripts/test.assets.sh
  scripts/update.default-content.sh
  scripts/update.theme-config.sh
  tests/bats/assets.subtheme.custom.bats
  tests/bats/assets.subtheme.sibling.bats
Labels: State: DO NOT MERGE, State: Do not review

#1189 Issue #3414202 by alex.skrypnyk, joshua1234511: Search page does not look as per design
  web/themes/contrib/civictheme/config/optional/views.view.civictheme_search.yml
  web/themes/contrib/civictheme/includes/views.inc
Labels: State: Ready to be merged

#1202 Updated Rector rules.
  .ahoy.yml
  composer.lock
  rector.php
  web/modules/custom/civictheme_dev/src/EventSubscriber/CivicthemeDevConfigDevelSubscriber.php
  web/modules/custom/cs_generated_content/src/CsGeneratedContentCivicthemeTrait.php
  web/modules/custom/cs_generated_content/src/CsGeneratedContentHelper.php
  web/themes/contrib/civictheme/.devtools/lint.sh
  web/themes/contrib/civictheme/.editorconfig
  web/themes/contrib/civictheme/phpcs.xml
  web/themes/contrib/civictheme/phpmd.xml
  web/themes/contrib/civictheme/phpstan.neon
  web/themes/contrib/civictheme/rector.php
Labels: State: Ready to be merged

#1207 Issue #3415747 by joshua1234511: Search for Component title / summary field is not working
  tests/behat/features/search.feature
  web/themes/contrib/civictheme/config/optional/search_api.index.civictheme_content.yml
Labels: State: Needs review
