Repository civictheme/monorepo-drupal, pull requests merged in 2024-02, with the labels that each got.

#1211 Updated containers to 24.1.0.
  .circleci/config.yml
  .docker/cli.dockerfile
  .docker/cli.onlytheme.dockerfile
  .docker/cli.sibling.dockerfile
  .docker/mariadb.dockerfile
  .docker/nginx-drupal.dockerfile
  .docker/php.dockerfile
  docker-compose.yml
  web/themes/contrib/civictheme/includes/link.inc
  web/themes/contrib/civictheme/includes/utilities.inc
Labels: State: Ready to be merged, Type: Chore

#1212 Updated Composer deps.
  composer.lock
  tests/behat/bootstrap/FeatureContext.php
Labels: State: Ready to be merged, Type: Chore

#1182 Issue #3415660 by govind.maloo: Arrows supporting Previous and Next buttons on webforms are not rendering as expected
  tests/behat/features/webform.feedback.render.feature
  web/themes/contrib/civictheme/civictheme.info.yml
  web/themes/contrib/civictheme/civictheme_starter_kit/templates/form/input--submit.html.twig
  web/themes/contrib/civictheme/config/install/webform.webform.civictheme_feedback.yml
  web/themes/contrib/civictheme/includes/form.inc
  web/themes/contrib/civictheme/templates/form/input--submit.html.twig
  web/themes/contrib/civictheme/templates/webform/webform.html.twig
Labels: State: Needs review

#1214 Issue #3415751 by joshua1234511: Fixed Duplicated checkboxes to show dependent colours on sub-theme settings.
  web/themes/contrib/civictheme/theme-settings/civictheme.theme-settings.colors.js
Labels: State: Needs review

#1206 Issue #3415737 by joshua1234511: Added provision for Media tags vocabulary.
  tests/behat/features/media_type.fields.feature
  tests/behat/features/views.view.civictheme_media.feature
  tests/behat/features/vocabulary.civictheme_media_tags.feature
  web/themes/contrib/civictheme/civictheme.info.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_audio.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_audio.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_document.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_document.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_icon.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_icon.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_image.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_image.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_remote_video.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_remote_video.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_video.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.media.civictheme_video.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_form_display.taxonomy_term.civictheme_media_tags.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_audio.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_audio.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_document.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_document.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_icon.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_icon.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_image.component.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_image.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_image.embedded.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_image.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.full.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_remote_video.media_library.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.full.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.media.civictheme_video.media_library.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_audio.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_document.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_icon.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_image.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_remote_video.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.field.media.civictheme_video.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/field.storage.media.field_c_m_media_tags.yml
  web/themes/contrib/civictheme/config/install/taxonomy.vocabulary.civictheme_media_tags.yml
  web/themes/contrib/civictheme/config/install/user.role.civictheme_content_author.yml
  web/themes/contrib/civictheme/config/install/user.role.civictheme_site_administrator.yml
  web/themes/contrib/civictheme/config/install/views.view.civictheme_media.yml
  web/themes/contrib/civictheme/tests/src/Functional/CivicthemeBrowserTestBase.php
  web/themes/contrib/civictheme/theme-settings.provision.inc
Labels: State: Requires more work

#1217 [#3415754] Added behat test.
  tests/behat/features/publishing_workflow.feature
Labels: State: Needs review
