Repository civictheme/monorepo-drupal, pull requests merged in 2025-07, with the labels that each got.

#1345 [#3508583] Updated field descriptions for Limit fields on Automated list.
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_limit.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_automated_list.field_c_p_list_limit_type.yml
Labels: State: Needs review, 1.11

#1392 Issue #3527182: Remove examples from civictheme_starter_kit
  tests/bats/assets.subtheme.custom.bats
  tests/bats/assets.subtheme.sibling.bats
  tests/phpunit/CivicthemeCreateSubthemeScriptUnitTest.php
  web/themes/contrib/civictheme/civictheme_create_subtheme.php
  web/themes/contrib/civictheme/civictheme_starter_kit/components/01-atoms/demo-button/demo-button.js
  web/themes/contrib/civictheme/civictheme_starter_kit/components/01-atoms/demo-button/demo-button.scss
  web/themes/contrib/civictheme/civictheme_starter_kit/components/01-atoms/demo-button/demo-button.stories.js
  web/themes/contrib/civictheme/civictheme_starter_kit/components/01-atoms/demo-button/demo-button.twig
  web/themes/contrib/civictheme/civictheme_starter_kit/components/02-molecules/navigation-card/navigation-card.stories.js
  web/themes/contrib/civictheme/civictheme_starter_kit/components/02-molecules/navigation-card/navigation-card.twig
  web/themes/contrib/civictheme/civictheme_starter_kit/components/03-organisms/header/header.twig
Labels: State: Needs review

#1363 Issue #3512939 by richardgaunt, fionamorrison23: incorrectly turns email addresses into links
  web/themes/contrib/civictheme/config/install/editor.editor.civictheme_rich_text.yml
  web/themes/contrib/civictheme/config/install/filter.format.civictheme_rich_text.yml
  web/themes/contrib/civictheme/includes/link.inc
Labels: State: Ready to be merged

#1340 Issue #3507328: Message - new paragraph component
  package-lock.json
  package.json
  tests/behat/features/paragraph.civictheme_message.fields.feature
  tests/behat/features/paragraph.civictheme_message.render.feature
  web/themes/contrib/civictheme/civictheme.info.yml
  web/themes/contrib/civictheme/civictheme.theme
  web/themes/contrib/civictheme/config/install/core.entity_form_display.paragraph.civictheme_message.default.yml
  web/themes/contrib/civictheme/config/install/core.entity_view_display.paragraph.civictheme_message.default.yml
  web/themes/contrib/civictheme/config/install/field.field.node.civictheme_page.field_c_n_components.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_background.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_content.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_message_type.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_theme.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_title.yml
  web/themes/contrib/civictheme/config/install/field.field.paragraph.civictheme_message.field_c_p_vertical_spacing.yml
  web/themes/contrib/civictheme/config/install/field.storage.paragraph.field_c_p_message_type.yml
  web/themes/contrib/civictheme/config/install/paragraphs.paragraphs_type.civictheme_message.yml
  web/themes/contrib/civictheme/includes/message.inc
  web/themes/contrib/civictheme/package-lock.json
  web/themes/contrib/civictheme/package.json
  web/themes/contrib/civictheme/templates/paragraphs/paragraph--civictheme-message.html.twig
Labels: State: Ready to be merged, 1.12

#1399 Issue #3501085 by richardgaunt, fionamorrison23, nidhish, joshua1234511: images with 'image style' should have relative link
  web/themes/contrib/civictheme/includes/media.inc
  web/themes/contrib/civictheme/includes/utilities.inc
Labels: State: Needs review

#1401 Issue #3482790 by joshua1234511, richardgaunt, ameymudras, lavanyatalwar, fionamorrison23: Logo path with space causes issue.
  web/themes/contrib/civictheme/src/Settings/CivicthemeSettingsFormSectionBase.php
Labels: State: Needs review

#1395 Issue #3533316: Includes using the subtheme namespace do not work in storybook.
  web/themes/contrib/civictheme/.storybook/sdc-plugin.js
  web/themes/contrib/civictheme/civictheme_starter_kit/.storybook/sdc-plugin.js
  web/themes/contrib/civictheme/civictheme_starter_kit/vite.config.js
Labels: State: Needs review
